In [2]:
import numpy as np
from src.od_matrix_completion.core import Problem, SubgradientDescent

n_z = 3
A = np.eye(n_z * n_z)
f = np.arange(1, n_z * n_z + 1, dtype=float)
D_hat = np.ones((n_z, n_z))
L = np.array([3.0, 6.0, 12.0])
W = np.array([7.0, 7.0, 7.0])

prob = Problem(A=A, f_obs=f, D_hat=D_hat, L=L, W=W, gamma=0.1)
opt = SubgradientDescent(step_size=1e-2, schedule="linear", project_marginals=True, ipf_iters=2, max_iters=500, verbose=True)
res = prob.solve(algorithm=opt)
print("objective=", res.objective, "iters=", res.n_iters)
print(res.D)

[SGD] it=1 obj=4.287953e+01 |g|=8.916e+00 step=1.629e-03 eta=1.000e-02
objective= 42.87944154167984 iters= 12
[[1. 1. 1.]
 [2. 2. 2.]
 [4. 4. 4.]]


In [3]:
import numpy as np
from src.od_matrix_completion.core import Problem, KLProximalDescent

n_z = 3
A = np.eye(n_z * n_z)
f = np.arange(1, n_z * n_z + 1, dtype=float)
D_hat = np.ones((n_z, n_z))
L = np.array([3.0, 6.0, 12.0])
W = np.array([7.0, 7.0, 7.0])

prob = Problem(A=A, f_obs=f, D_hat=D_hat, L=L, W=W, gamma=0.1)
opt = KLProximalDescent(step_size=1e-2, schedule="sqrt", project_marginals=True, ipf_iters=2, max_iters=500, verbose=True)
res = prob.solve(algorithm=opt)
print("objective=", res.objective, "iters=", res.n_iters)
print(res.D)

[ProxKL] it=1 obj=4.287944e+01 step=1.826e+00 eta=1.000e-02
objective= 42.87944154167984 iters= 2
[[1. 1. 1.]
 [2. 2. 2.]
 [4. 4. 4.]]
